### PR TITLE
Added a simple frontend project

### PR DESCRIPTION
**Pull request by devrudra9**

### CODE REVIEW

**Comment by devrudra9** [comment]
Please merge my PR #11 @sanskarsri .. hoping this won't be creating any conflicts again :/

**Comment by sanskarsri** [comment]
> Please merge my PR #11 @sanskarsri .. hoping this won't be creating any conflicts again :/

Yes it's not causing any conflicts now you just have to do one change then your PR is ready for merge
... just link your project as other projects are added in Projects section

**Comment by devrudra9** [comment]
Done ... now please merge it @sanskarsri

**Comment by sanskarsri** [comment]
> Done ... now please merge it @sanskarsri

merged successfully

**Pull request merged**
